<a href="https://colab.research.google.com/github/Antoni018/Sistemasdistribuidos/blob/main/Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importar numpy y ver la version
import numpy as np
print(np.__version__)


1.25.2


In [ ]:
# create 1d array of numbers from 0 to 9

import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [6]:
# create random vector of size 10 and replace the maximun value by 0

import numpy as np

Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)


[0.13328049 0.13788552 0.80807671 0.53666804 0.21192783 0.78033709
 0.9070298  0.63848795 0.43554972 0.63769879]
[0.13328049 0.13788552 0.80807671 0.53666804 0.21192783 0.78033709
 0.         0.63848795 0.43554972 0.63769879]


In [20]:
# print the number 8 from the array below:

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [8]:
# print the numbers [3,4,5] from the array below: arr=np.array([1,2,3,4,5,6,7])

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[2:5])


[1 2 3 4 5 6 7]
[3 4 5]


In [9]:
# print the last 4 numbers from the array below: arr=np.array([1,2,3,4,5,6,7])

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[-4:])


[1 2 3 4 5 6 7]
[4 5 6 7]


In [10]:
# create a 3x3 numpy array of all true's

import numpy as np
arr = np.full((3, 3), True)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# extract all odd numbers from arr

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

impares = arr[arr % 2 == 1]
print(arr)
print(impares)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [12]:
# create a vector with values ranging from 10 to 49

import numpy as np
vector = np.arange(10,50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
# reverse a vector (first element becomes last)

import numpy as np
vector = np.arange(10,50)

reversed_vector = vector[::-1]
print(vector)
print(reversed_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [15]:
# create a 10x10 array with random integer values and find the minium and maximun values

import numpy as np
arr = np.random.randint(100, size=(10, 10))

min_value = np.min(arr)
max_value = np.max(arr)

print(arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


[[57 61 46 33 89 25 72 52 44 39]
 [72  3  8 31 67 83  1 34 35 62]
 [60 30 85 50 71 58 75 45 59 39]
 [10 19 56 79 97  6 66 83 22 47]
 [ 5 68 15 47 91 84 24 97 11 62]
 [33 94 12 11 15 58  2 81 10 66]
 [16 44  6 59 37 39 68  6 37 83]
 [14 62 85 51 33 26 49 11 67 50]
 [36 27 60 36 30 26 79 15 49 33]
 [99 12 41 90 39 41 24 63 35 81]]
Minimum value: 1
Maximum value: 99


In [16]:
# create a 3x3x3 array with random integer values

import numpy as np
arr = np.random.randint(100, size=(3, 3, 3))
print(arr)


[[[75 37 45]
  [67 17 63]
  [31 82 61]]

 [[28 55 73]
  [49 10 63]
  [93 87 72]]

 [[75 91  8]
  [38 78 80]
  [38 91 78]]]


In [17]:
# replace all odd numbers in arr with -1

arr[arr % 2 == 1] = -1
print(arr)


[[[-1 -1 -1]
  [-1 -1 -1]
  [-1 82 -1]]

 [[28 -1 -1]
  [-1 10 -1]
  [-1 -1 72]]

 [[-1 -1  8]
  [38 78 80]
  [38 -1 78]]]


In [18]:
# create an array of type float

import numpy as np

float_array = np.array([1.2, 3.4, 5.6, 7.8, 9.0], dtype=np.float32)
print(float_array)


[1.2 3.4 5.6 7.8 9. ]


In [ ]:
# convert a 1d array to a 2d array with 2 rows

import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a)
a = a.reshape(2,5)
print(a)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# How to find common values between two arrays?
# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)

import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))


[6 9 4 9 7 2 1 6 0 0]
[1 7 3 8 8 6 6 9 5 9]
[1 6 7 9]


In [34]:
# Consider two random array A and B, check if they are equal
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

import numpy as np
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal_arrays = np.array_equal(A,B)
print(equal_arrays)


[1 0 1 1 0]
[1 0 1 1 0]
True


In [38]:
# Stack arrays a and b vertically

import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print(b)

c = np.vstack([a, b])
print(c)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [39]:
# Stack arrays a and b vertically

import numpy as np
d = np.hstack([a,b])
print(d)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [40]:
# Get all items between 5 and 10 from array tmp.

import numpy as np
tmp = np.array([2, 6, 1, 9, 10, 3, 27])
tmp[(tmp >= 5) & (tmp <= 10)]


array([ 6,  9, 10])

In [41]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

import numpy as np
def pair_max(x, y):
  """Get the maximum of two items"""
  return np.where(x > y, x, y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)


array([6, 7, 9, 8, 9, 7, 5])

In [42]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1, 0]] = arr[:, [0, 1]]
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [44]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

import numpy as np
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)


[[7.44079493 7.25494133 5.13117208]
 [6.55701632 6.46452927 8.26920691]
 [8.67103156 5.89411062 6.22847498]
 [8.16043393 9.78900138 7.90480274]
 [6.15837021 8.49426901 7.35896456]]
